<?php

/**
 * @file
 * For the theme hook.
 */

/**
 * Implements custom_form_theme()
 *
 * @param array $existing
 *   An array of existing theme definitions.
 * @param string $type
 *   The type of theme hook being implemented.
 * @param string $theme
 *   The name of the theme implementing the hook.
 * @param string $path
 *   The path to the theme or module containing the hook implementation.
 *
 * @return array
 *   An associative array of theme definitions.
 */
function custom_form_theme($existing, $type, $theme, $path) {
  return [
    'custom_form_data' => [
      'variables' => [
        'content' => [],
        'anchorReference' => '',
        'description' => '',
        'latestNews' => [],
      ],
      'template' => 'custom-form-data',
    ],
  ];
}
